/*

 GAMEBOARDBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\nicka\Downloads\gbtd22\tic_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundWidth 20
#define backgroundHeight 18
#define backgroundBank 0

extern unsigned char background[];
extern unsigned char diagRight[];
extern unsigned char diagLeft[];
extern unsigned char vertLeft[];
extern unsigned char vertMid[];
extern unsigned char vertRight[];
extern unsigned char horTop[];
extern unsigned char horMid[];
extern unsigned char horBot[];

/* End of GAMEBOARDBACKGROUND.H */
